global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alertmanager configuration will be added here

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'captcha-service'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'